---
jobs:
  docker-lint:
    docker:
      - image: vpgrp/linter:docker-lint
    steps:
      - checkout
      - run:
          name: docker linting
          command: /usr/bin/docker-lint Dockerfile
  markdown-lint:
    docker:
      - image: vpgrp/linter:markdown-lint
    steps:
      - checkout
      - run:
          name: markdown linting
          command: /usr/bin/markdown-lint .
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: apk add --no-cache git
      - run: |
          docker build --build-arg VCS_REF=`git rev-parse --short HEAD` \
                       --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
                       --tags sdesbure/hddtemp:latest .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push sdesbure/hddtemp:latest
workflows:
  version: 2
  lint:
    jobs:
      - docker-lint
      - markdown-lint
      - build:
          requires:
            - docker-lint
            - markdown-lint
